server:
  #https监听端口
  port: 8901
#  custom:
#    #http监听端口
#    httpPort: 8898
#  ssl:
#    key-store: classpath:qftty.cn.jks
#    key-store-password: 123456
#    key-store-type: JKS
#    #key-alias: qftty #证书别名
spring:
  application:
    name: kaijiang
  datasource:   #数据库信息
    username: chinaman**ChenJi#Yang
    password: ChenJi*915728#And%_JiangA%^@#tYU_077099
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://132.232.222.50:3306/testzkao46?autoReconnect=TRUE&useUnicode=TRUE&characterEncoding=UTF-8&useSSL=FALSE&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cj.**
daas-switch:
  swagger-open: true

logging:
  level.root: info
  level.com.stylefeng: info
  path: logs/
  file: kaijiang.log

#quartzJob
quartz:
  cron:
    test: 0/5 * * * * ?


